services:
  django:
    build: .
    container_name: api-aiqfome
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - internal

  postgres:
    image: postgres:16
    container_name: db-aiqfome
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: aiqfome
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d aiqfome"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: cache-aiqfome
    restart: always
    expose:
      - "6379"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
